# Charge automatiquement tous les contrôleurs avec des attributs #[Route]
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes spécifiques (si nécessaire)
api_login:
    path: /api/login
    methods: ['POST']

api_register:
    path: /api/register
    methods: ['POST']
    controller: App\Controller\AuthController::register
